# Generated by Django 3.1.12 on 2021-08-03 09:56

import auth_app.sub_models.Answeres
import auth_app.sub_models.Note
import auth_app.sub_models.Posts
import auth_app.sub_models.Token
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthPrivilage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('FeedPosts', djongo.models.fields.ArrayField(model_container=auth_app.sub_models.Posts.Posts, model_form_class=auth_app.sub_models.Posts.PostsForm)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('QuestionId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Question', models.CharField(max_length=200)),
                ('DatePosted', models.DateTimeField()),
                ('AnsweresList', djongo.models.fields.ArrayField(model_container=auth_app.sub_models.Answeres.Answeres, model_form_class=auth_app.sub_models.Answeres.AnsweresForm)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('UserEmail', models.EmailField(max_length=50)),
                ('UserPassword', models.CharField(max_length=50)),
                ('UserAge', models.IntegerField()),
                ('Gender', models.CharField(max_length=200)),
                ('PostalCode', models.IntegerField()),
                ('DateRegistered', models.DateTimeField()),
                ('Notes', djongo.models.fields.ArrayField(model_container=auth_app.sub_models.Note.Note, model_form_class=auth_app.sub_models.Note.NoteForm)),
                ('Tokens', djongo.models.fields.ArrayField(model_container=auth_app.sub_models.Token.Token, model_form_class=auth_app.sub_models.Token.TokenForm)),
                ('Privilage', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralPrivilage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionList', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='auth_app.questions')),
            ],
        ),
    ]
