# Generated by Django 3.2.5 on 2021-07-25 08:32

import auth_app.sub_models.Note
import auth_app.sub_models.Token
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answeres',
            fields=[
                ('AnswereId', models.AutoField(primary_key=True, serialize=False)),
                ('Answere', models.CharField(max_length=200)),
                ('DatePosted', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AuthPrivilage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('AnswereList', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='auth_app.answeres')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('PostId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Image', models.BinaryField()),
                ('Descripton', models.CharField(max_length=200)),
                ('DatePosted', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('QuestionId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Question', models.CharField(max_length=200)),
                ('DatePosted', models.DateTimeField()),
                ('AnsweresList', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='auth_app.answeres')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50)),
                ('UserEmail', models.EmailField(max_length=50)),
                ('UserPassword', models.CharField(max_length=50)),
                ('UserAge', models.IntegerField()),
                ('Gender', models.CharField(max_length=200)),
                ('PostalCode', models.IntegerField()),
                ('DateRegistered', models.DateTimeField()),
                ('Notes', djongo.models.fields.ArrayField(model_container=auth_app.sub_models.Note.Note, model_form_class=auth_app.sub_models.Note.NoteForm)),
                ('Tokens', djongo.models.fields.ArrayField(model_container=auth_app.sub_models.Token.Token, model_form_class=auth_app.sub_models.Token.TokenForm)),
                ('AuthAccess', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='auth_app.authprivilage')),
                ('QuestionList', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='auth_app.questions')),
            ],
        ),
        migrations.AddField(
            model_name='authprivilage',
            name='FeedPosts',
            field=djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='auth_app.posts'),
        ),
    ]
